-- MySQL Script generated by MySQL Workbench
-- Fri Sep 16 11:09:49 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Terminal
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Terminal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Terminal` DEFAULT CHARACTER SET utf8 ;
USE `Terminal` ;

-- -----------------------------------------------------
-- Table `Terminal`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Terminal`.`usuarios` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `documento` VARCHAR(100) NOT NULL,
  `nombre` VARCHAR(200) NOT NULL,
  `apellido` VARCHAR(200) NOT NULL,
  `telefono` VARCHAR(100) NOT NULL,
  `correo` VARCHAR(300) NULL,
  `rol` ENUM("Administrador", "Auxiliar") NOT NULL,
  `usuario` VARCHAR(100) NULL,
  `contrasena` VARCHAR(200) NULL,
  `estado` ENUM("Activo", "Inactiva") NOT NULL,
  PRIMARY KEY (`id`),
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Terminal`.`egresos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Terminal`.`egresos` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `numeroComprobante` VARCHAR(300) NOT NULL,
  `fechaComprobante` VARCHAR(200) NULL,
  `nombreBeneficiario` VARCHAR(300) NOT NULL,
  `numeroIdentificacion` VARCHAR(100) NULL,
  `concepto` TEXT NULL,
  `numContrato` VARCHAR(300) NULL,
  `fechaContrato` VARCHAR(300) NULL,
  `usuarios_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_egresos_usuarios1_idx` (`usuarios_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `fk_egresos_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `Terminal`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Terminal`.`archivos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Terminal`.`archivos` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `numFolios` VARCHAR(300) NULL,
  `numEstante` VARCHAR(300) NULL,
  `nivelEstante` VARCHAR(300) NULL,
  `numCaja` VARCHAR(300) NULL,
  `numCarpeta` VARCHAR(300) NULL,
  `numComprobante` VARCHAR(300) NOT NULL,
  `numeroIdentificacion` VARCHAR(100) NULL,
  `egresos_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_archivos_egresos1_idx` (`egresos_id` ASC),
  CONSTRAINT `fk_archivos_egresos1`
    FOREIGN KEY (`egresos_id`)
    REFERENCES `Terminal`.`egresos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Terminal`.`ingresos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Terminal`.`ingresos` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `numeroCaja` VARCHAR(300) NULL,
  `numeroBoletin` VARCHAR(300) NOT NULL,
  `fecha` VARCHAR(200) NULL,
  `nombreBeneficiario` VARCHAR(800) NOT NULL,
  `numeroRecibo` VARCHAR(300) NULL,
  `concepto` TEXT NULL,
  `usuarios_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ingresos_usuarios1_idx` (`usuarios_id` ASC),
  CONSTRAINT `fk_ingresos_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `Terminal`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Terminal`.`talentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Terminal`.`talentos` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tipoDocumento` ENUM('C.C', 'C.E', 'T.I', 'R.C', 'Pasaporte') NOT NULL,
  `documento` VARCHAR(100) NOT NULL,
  `nombres` VARCHAR(200) NOT NULL,
  `apellidos` VARCHAR(200) NOT NULL,
  `estadoCivil` VARCHAR(200) NULL,
  `telefono` VARCHAR(200) NULL,
  `direccion` VARCHAR(300) NULL,
  `correo` VARCHAR(300) NULL,
  `estado` ENUM("Activo", "Inactiva") NOT NULL,
  `usuarios_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_talentos_usuarios1_idx` (`usuarios_id` ASC),
  CONSTRAINT `fk_talentos_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `Terminal`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Terminal`.`registros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Terminal`.`registros` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `numeroGaveta` VARCHAR(300) NULL,
  `numeroCarpetas` VARCHAR(300) NULL,
  `numeroFolios` VARCHAR(300) NULL,
  `numeroArchivador` VARCHAR(300) NULL,
  `documento` VARCHAR(100) NULL,
  `nombre` VARCHAR(200) NOT NULL,
  `apellido` VARCHAR(200) NOT NULL,
  `cargo` TEXT NOT NULL,
  `tipoVinculacion` VARCHAR(500) NULL,
  `estado` ENUM("Activo", "Inactiva") NOT NULL,
  `usuarios_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_registros_usuarios1_idx` (`usuarios_id` ASC),
  CONSTRAINT `fk_registros_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `Terminal`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Terminal`.`integrantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Terminal`.`integrantes` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `documentoTalento` VARCHAR(100) NOT NULL,
  `tipoDocumento` ENUM('C.C', 'C.E', 'T.I', 'R.C', 'Pasaporte') NOT NULL,
  `documentoFamiliar` VARCHAR(100) NULL,
  `nombreFamiliar` VARCHAR(200) NOT NULL,
  `apellidoFamiliar` VARCHAR(200) NOT NULL,
  `telefono` VARCHAR(200) NULL,
  `parentesco` VARCHAR(300) NOT NULL,
  `estado` ENUM("Activo", "Inactiva") NOT NULL,
  `talentos_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_integrantes_talentos1_idx` (`talentos_id` ASC),
  CONSTRAINT `fk_integrantes_talentos1`
    FOREIGN KEY (`talentos_id`)
    REFERENCES `Terminal`.`talentos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Terminal`.`libros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Terminal`.`libros` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `disposicionFinal` ENUM('C.T', 'E', 'P', 'MD', 'S') NOT NULL,
  `retencion` ENUM('0', '2', '5', '10', '15', '20', '25', '30', '35', '40', '45', '50', '55', '60', '65', '70', '75', '80', '85', '90', '95', '100') NOT NULL,
  `nivelLibro` VARCHAR(300) NULL,
  `estanteLibro` VARCHAR(300) NULL,
  `cantidad` VARCHAR(300) NULL,
  `numBoletin` VARCHAR(300) NULL,
  `numComprobante` VARCHAR(300) NULL,
  `mes` VARCHAR(300) NULL,
  `agenda` VARCHAR(300) NOT NULL,
  `usuarios_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_libros_usuarios1_idx` (`usuarios_id` ASC),
  CONSTRAINT `fk_libros_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `Terminal`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Terminal`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Terminal`.`empleado` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tipoContrato` VARCHAR(300) NOT NULL,
  `documento` VARCHAR(100) NOT NULL,
  `numeroContrato` VARCHAR(300) NULL,
  `inicioContrato` VARCHAR(300) NOT NULL,
  `finContrato` VARCHAR(300) NULL,
  `cargo` VARCHAR(300) NOT NULL,
  `prorroga1` TEXT NULL,
  `prorroga2` TEXT NULL,
  `prorroga3` TEXT NULL,
  `prorroga4` TEXT NULL,
  `estado` ENUM("Activo", "Inactiva") NOT NULL,
  `talentos_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_empleado_talentos1_idx` (`talentos_id` ASC),
  CONSTRAINT `fk_empleado_talentos1`
    FOREIGN KEY (`talentos_id`)
    REFERENCES `Terminal`.`talentos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Terminal`.`seguros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Terminal`.`seguros` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `documento` VARCHAR(100) NOT NULL,
  `salud` VARCHAR(500) NULL,
  `riegosLaborales` VARCHAR(500) NULL,
  `pension` VARCHAR(500) NULL,
  `estado` ENUM("Activo", "Inactiva") NOT NULL,
  `talentos_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_seguros_talentos1_idx` (`talentos_id` ASC),
  CONSTRAINT `fk_seguros_talentos1`
    FOREIGN KEY (`talentos_id`)
    REFERENCES `Terminal`.`talentos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Terminal`.`documentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Terminal`.`documentos` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `talentoDocumento` VARCHAR(100) NOT NULL,
  `fechaNacimiento` VARCHAR(200) NULL,
  `fechaExpedicion` VARCHAR(200) NULL,
  `ruta` VARCHAR(300) NULL,
  `estado` ENUM("Activo", "Inactiva") NOT NULL,
  `talentos_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_documentos_talentos1_idx` (`talentos_id` ASC),
  CONSTRAINT `fk_documentos_talentos1`
    FOREIGN KEY (`talentos_id`)
    REFERENCES `Terminal`.`talentos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Terminal`.`archiveros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Terminal`.`archiveros` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `numBoletin` VARCHAR(300) NOT NULL,
  `numRecibo` VARCHAR(300) NOT NULL,
  `numEstante` VARCHAR(300) NULL,
  `numFolios` VARCHAR(300) NULL,
  `numCaja` VARCHAR(300) NULL,
  `nivelEstante` VARCHAR(300) NULL,
  `numCarpeta` VARCHAR(300) NULL,
  `ingresos_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_archiveros_ingresos1_idx` (`ingresos_id` ASC),
  CONSTRAINT `fk_archiveros_ingresos1`
    FOREIGN KEY (`ingresos_id`)
    REFERENCES `Terminal`.`ingresos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
